clean:
	rm -f 11.Etoiles
	rm -f 12.Conversions
	rm -f 13.MultiplicationEgyptienne
	rm -f 15.NombresPremiers
	rm -f 16.NombresAmis

run11: 11.Etoiles.c
	gcc -Wall -o 11.Etoiles 11.Etoiles.c
	./11.Etoiles

run12: 12.Conversions.c
	gcc -Wall -o 12.Conversions 12.Conversions.c
	./12.Conversions

run13: 13.MultiplicationEgyptienne.c
	gcc -Wall -o 13.MultiplicationEgyptienne 13.MultiplicationEgyptienne.c
	./13.MultiplicationEgyptienne

run15: 15.NombresPremiers.c
	gcc -Wall -o 15.NombresPremiers 15.NombresPremiers.c
	./15.NombresPremiers

run16: 16.NombresAmis.c
	gcc -Wall -o 16.NombresAmis 16.NombresAmis.c
	./16.NombresAmis

