clean:
	rm -f Etoiles
	rm -f Conversions
	rm -f MultiplicationEgyptienne
	rm -f NombresPremiers
	rm -f NombresAmis

Etoiles: Etoiles.c
	gcc -Wall -o Etoiles Etoiles.c
	./Etoiles
	rm -f Etoiles
	
Conversions: Conversions.c
	gcc -Wall -o Conversions Conversions.c
	./Conversions
	rm -f Conversions

MultiplicationEgyptienne: MultiplicationEgyptienne.c
	gcc -Wall -o MultiplicationEgyptienne MultiplicationEgyptienne.c
	./MultiplicationEgyptienne
	rm -f MultiplicationEgyptienne

NombresPremiers: NombresPremiers.c
	gcc -Wall -o NombresPremiers NombresPremiers.c
	./NombresPremiers
	rm -f NombresPremiers

NombresAmis: NombresAmis.c
	gcc -Wall -o NombresAmis NombresAmis.c
	./NombresAmis
	rm -f NombresAmis
